# Generated by Django 2.2 on 2019-04-27 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharpen',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='tools',
            name='stock_code',
            field=models.IntegerField(verbose_name='Código'),
        ),
    ]
