# Generated by Django 2.2 on 2019-04-27 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharp', '0002_auto_20190427_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharpen',
            name='tools',
        ),
        migrations.AddField(
            model_name='sharpen',
            name='tools',
            field=models.ManyToManyField(related_name='description', to='sharp.Tools', verbose_name='Ferramenta'),
        ),
    ]
