# Generated by Django 2.2 on 2019-04-28 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sharp', '0003_auto_20190427_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharpen',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='sharpen',
            name='tools',
        ),
        migrations.AlterField(
            model_name='tools',
            name='factory_name',
            field=models.CharField(max_length=150, verbose_name='Nome de Fábrica'),
        ),
        migrations.AlterField(
            model_name='tools',
            name='internal_description',
            field=models.CharField(max_length=150, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='tools',
            name='manufacturer',
            field=models.CharField(max_length=100, verbose_name='Fabricante'),
        ),
        migrations.CreateModel(
            name='ListSharpen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantidade')),
                ('sharpen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Lista', to='sharp.Sharpen')),
                ('tools', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='description', to='sharp.Tools', verbose_name='Ferramenta')),
            ],
        ),
    ]
